ALTER TABLE transfers ADD COLUMN source_debited BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE transfers ADD COLUMN destination_credited BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE transfers ADD COLUMN compensation_completed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE transfers ADD COLUMN reversed_at TIMESTAMP WITH TIME ZONE;